# Tinkering with connecting to MongoDB
Be sure to have a copy of ncba_config that defines two variables:
`ncba_db_user` and `ncba_db_pass`


```{r}
if (!require(mongolite))
  install.packages(
    "mongolite", repos = "http://cran.us.r-project.org"
  )

HOST = "cluster0-shard-00-00.rzpx8.mongodb.net:27017"
DB = "ebd_mgmt"
COLLECTION = "ebd"
source("ncba_config.r")

URI = sprintf(
  paste0("mongodb://%s:%s@%s/%s?authSource=admin&replicaSet=",
    "atlas-3olgg1-shard-0&readPreference=primary&ssl=true"),
  ncba_db_user,
  ncba_db_pass,
  HOST,
  DB)
```

```{r}
# connect to a specific collection (table)
m <- mongo(
  COLLECTION,
  url = URI,
  options = ssl_options(weak_cert_validation = T)
)

m_block_summaries <- mongo(
  "BLOCK_SUMMARIES",
  url = URI,
  options = ssl_options(weak_cert_validation = T))
```

```{r}
species <- "Cerulean Warbler"
pipeline <- sprintf(
  '[
    {
      "$unwind":
        {
          "path": "$sppList"
        }
    },
    {
      "$match": {
          "sppList.COMMON_NAME": "%s"
        }
    },
    {
      "$project":
        {
          "_id" : 0,
          "ID_NCBA_BLOCK": 1,
          "bc": "$sppList.breedMaxCategory"
        }
    }
  ]',
  species
)
mongodata <- m_block_summaries$aggregate(pipeline)
```

# bsl <- block_spp_lists(
#   "35080H4SE"
# )

# print(head(bsl))
# print(nrow(bsl))

# breeding_map("Wood Duck")